name: Build EUD with doc.ctor

on:
  workflow_dispatch:

jobs:
  eud-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger internal workflow via GitHub API
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DOCCTOR_ACTIONS_API_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/DevExpress/doc.ctor-actions/actions/workflows/eud.yml/dispatches \
            -d '{
              "ref":"main",
              "inputs": {
                "source_branch": "${{ github.ref_name}}",
                "content_stamp": "${{ github.sha }}"
              }
            }'
